language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
before_install: sudo apt-get install unzip
before_script:
  - export TFVER=0.13.4
  - export TFURL=https://releases.hashicorp.com/terraform/
  - TFURL+=$TFVER
  - TFURL+="/terraform_"
  - TFURL+=$TFVER
  - TFURL+="_linux_amd64.zip"
  - wget $TFURL -O terraform_bin.zip
  - mkdir tf_bin
  - unzip terraform_bin.zip -d tf_bin
install:
  - curl https://bootstrap.pypa.io/ez_setup.py -o - | python
  - pip install .
script:
  - export PATH=$PATH:$PWD/tf_bin
  - pytest -v
branches:
  only:
    - master
    - develop
    - release/**
